### ISSUE TITLE
Pipe '|' symbol breaks YAML Syntax highlighting

### ISSUE THREAD

**Issue by ghost** [Codiad/Codiad#480]
Example yaml

```
groups:
  Guest:
    default: true
    prefix: '&7[&fG&7]&f '
    options:
      rank: '1000'
    permissions:
    - test.ok.*
    - test.fails.here(|.*)
    - all.entries.after.show.as.bad.syntax
```
